### ISSUE TITLE
Improve syntax colorizer for Papyrus script types.

### ISSUE THREAD

**Issue by Scrivener07** [joelday/papyrus-lang#128]
**Is your feature request related to a problem? Please describe.**
Script types such as form, etc, are not recognised as symbols for syntax colouring purposes.

**Describe the solution you'd like**
Preferably a way to contextually colorize all valid script types in a project space.

**Describe alternatives you've considered**
There may be a rule pattern Im unaware of that makes this easier but the solution Im familiar with is to add all the known script names to the [papyrus.tmLanguage](https://github.com/joelday/papyrus-lang/blob/master/src/papyrus-lang-vscode/syntaxes/papyrus/papyrus.tmLanguage). Maintaining a static list of names is not optimal.

**Additional context**
Properties and variables don't get highlights for script types.
![Capture](https://user-images.githubusercontent.com/1912967/69506109-21827780-0efb-11ea-9e96-d423f2e81dc5.PNG)

_This issue was brought up by the user `Antithesis` on Discord, thanks!_

**Comment by joelday** [comment]
Well as soon as we can get this release out, this is good to go.
