### ISSUE TITLE
[Fallout 4] Compilation Error: filename does not match script name

### ISSUE THREAD

**Issue by Gavvers** [joelday/papyrus-lang#131]
I am encountering this error while compiling Fallout 4 scripts. One such script is DLC03:TrapBear, the error message is as follows,

> Scripts\Source\User\DLC03\TrapBear.psc(0,0): filename does not match script name: "dlc03:trapbear" expected: "TrapBear"
> No output generated for DLC03:TrapBear.psc, compilation failed.

The error seems to be saying that to fix it, the script _DLC03:TrapBear_ should be renamed to _TrapBear_, but ... this is an override of a Bethesda script so I don't think that is the correct fix. How do I deal with this?

I am compiling from the CLI using a Papyrus project file and no amount of tweaking of my imports makes any difference. My project file with my much-tweaked and in-progress imports list (sanitized) is below:

```
<?xml version='1.0'?>
<PapyrusProject
	xmlns="PapyrusProject.xsd"
	Flags="Fallout4OfficialScriptsDir\Scripts\Source\Base\Institute_Papyrus_Flags.flg"
	Output="MyMod\Scripts"
	Optimize="true"
	Release="true"
	Final="true">
    <Import>MyMod\Scripts\Source\User\DLC03\Fragments</Import>
    <Import>MyMod\Scripts\Source\User\DLC03</Import>
    <Import>MyMod\Scripts\Source\User\Fragments</Import>
    <Import>MyMod\Scripts\Source\User\Hardcore</Import>
    <Import>MyMod\Scripts\Source\User\UFO4P</Import>
    <Import>MyMod\Scripts\Source\User</Import>
    <Import>ModsDir\f4se_0_06_20\Scripts\Source\User</Import>
    <Import>Fallout4OfficialScriptsDir\Scripts\Source\DLC03\Fragments</Import>
    <Import>Fallout4OfficialScriptsDir\Scripts\Source\DLC03</Import>
    <Import>Fallout4OfficialScriptsDir\Scripts\Source\Base\CreationClub</Import>
    <Import>Fallout4OfficialScriptsDir\Scripts\Source\Base\Fragments</Import>
    <Import>Fallout4OfficialScriptsDir\Scripts\Source\Base\Hardcore</Import>
    <Import>Fallout4OfficialScriptsDir\Scripts\Source\Base</Import>
    <Scripts>
        <Script>DLC03:TrapBear.psc</Script>
    </Scripts>
</PapyrusProject>
```

My CLI command, run from a batch file (the variable logfile is generated each time):

`"Fallout4Dir\Papyrus Compiler\PapyrusCompiler.exe" MyMod.ppj -ignorecwd >  "%logfile%" 2>&1`

**Comment by Scrivener07** [comment]
* Dont put the `psc` file extension in the `<Script>` element. It's the `ScriptName` not the file name.

`E:\Games\Steam\steamapps\common\Fallout 4\Data\Scripts\Source\DLC\DLC03`
![Capture](https://user-images.githubusercontent.com/1912967/71775323-f012b800-2f4c-11ea-911a-2f1906661b71.PNG)

```
<?xml version='1.0'?>
<PapyrusProject xmlns="PapyrusProject.xsd"
	Flags="Institute_Papyrus_Flags.flg"
	Output="E:\Games\Steam\steamapps\common\Fallout 4\Data\Scripts"
	Asm="Discard"
	Optimize="false"
	Release="false"
	Final="false">
	<Imports>
		<Import>.</Import>
		<Import>E:\Games\Steam\steamapps\common\Fallout 4\Data\Scripts\Source\DLC</Import>
		<Import>E:\Games\Steam\steamapps\common\Fallout 4\Data\Scripts\Source\Base</Import>
	</Imports>
	<Scripts>
		<Script>DLC03:TrapBear</Script>
	</Scripts>
</PapyrusProject>
```

```
e:\Games\Steam\steamapps\common\Fallout 4\Data\Scripts\Source\User>CALL "..\..\..\..\Papyrus Compiler\PapyrusCompiler" "..\User\Creation Kit - User.ppj"
Papyrus Compiler Version 2.8.0.4 for Fallout 4
Copyright (C) ZeniMax Media. All rights reserved.
Starting 1 compile threads for 1 files...
Compiling "DLC03:TrapBear"...
Compilation succeeded.

Batch compile of 1 files finished. 1 succeeded, 0 failed.
```

**Comment by Gavvers** [comment]
Wow, thanks @Scrivener07 !

I did not realize that the DLC directories needed to be one level down from the Base/ directory level. 

From the documentation, example 2 in the [wiki](https://github.com/joelday/papyrus-lang/wiki/Papyrus-Project)

`<Import>C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\Scripts\`**Source\DLC01**`</Import>`

Maybe that should be changed to insert the DLC/ directory between Source/ and DLC01?

The documentation also says,

> `<Scripts>` Element
> ...
> It consists of several <Script> elements which specify the script files the compiler should build. Namespaces may be specified using path separators or colons. **File extension is optional.**

So it seems to not be true that the file extension in optional in a <script> element?

Anyway, thanks a ton!

**Comment by Scrivener07** [comment]
No problem :)

**Comment by Scrivener07** [comment]
Yea general papyrus docs are an ongoing thing and much of it was inherited from the CreationKit.com
