### ISSUE TITLE
Extension host terminated unexpectedly. 

### ISSUE THREAD

**Issue by CarlosLeyvaAyala** [joelday/papyrus-lang#143]
Installing on a brand new computer, VS Code 1.48.2. 
No matter what version of this plugin I install, I get that error and the JS console tells me it was 
`System.FormatException: A duplicate key 'Papyrus:sScriptSourceFolder' was found. `
at 
`joelday.papyrus-lang-vscode-2.23.0\dist\PapyrusExtension.js:12925`

I used this with no issues on an old computer. Sadly, I lost it, so I can't compare both setups.

**Comment by joelday** [comment]
@CarlosLeyvaAyala Can you check your .ini files to see if sScriptSourceFolder has been written more than once in any of them?

**Comment by CarlosLeyvaAyala** [comment]
Ugh. I'm feeling quite inadequate xD

Yeah, turned out I somehow had that line tripled in my CreationKit.ini. 
I was searching all around for that line in the VsCode settings and such, but never thought it was a good ole' Creation Kit configuring problem.

Thank you so much!
