### ISSUE TITLE
Document This retirement

### ISSUE THREAD

**Issue by prometheas** [joelday/papyrus-lang#144]
Feel free to delete this, @joelday, but I could find no other means to contact you about the fate of your defunct Document This extension, and the unfortunate way that its retirement was handled, without any messaging about its discontinuation nor any attempt to hand it over to a new maintainer or message its end of life in the README, etc., leaving a random assortment of 58 forks in its wake.

It's likely too late to make any meaningful impact on the fate of the Document This extension now, but I would hope that—at least for the projects you continue to support today—you'll reconsider how you might go about retiring these projects when their time comes.

Anyway, I do realize that filing an issue on an unrelated repository isn't that useful (and how it's in fact merely "noise", contextually speaking), and wish I could have provided this feedback in a more fruitful (and slightly less public) way.

Hope you and your loved ones remain safe and healthy.

**Comment by joelday** [comment]
Thank you for reaching out, @prometheas. I agree that it was not done as gracefully as I would hope to see from the maintainers of the projects that I rely on personally. I will keep that in mind for future projects.
