### ISSUE TITLE
The skyrimSpecialEdition server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by hoskonen** [joelday/papyrus-lang#150]
**Describe the bug**
Not sure if this is because new version of latest Skyrim Anniversary Edition, but every time i'm opening VSCode and papyrus scripts i get the message that says:

The skyrimSpecialEdition server crashed 5 times in the last 3 minutes. The server will not be restarted.

Building scripts work ok, but i don't get intellisense, or to get payrus debugger to work, i would be happy if only the intellisense would work.

**To Reproduce**
Open VSCode with and papyrus script

1. ...

Internal Error - System.AggregateException: One or more errors occurred. ---> System.FormatException: Unrecognized line format: 'iExtendedResponceLength+255'. at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload) at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load() at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers) at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build() at DarkId.Papyrus.LanguageService.Configuration.CreationKit.CreationKitInisConfigLoader.LoadConfig(CreationKitIniLocations inis) in D:\a\papyrus-lang\papyrus-lang\src\DarkId.Papyrus.LanguageService\Configuration\CreationKit\CreationKitInisConfigLoader.cs:line 27 at DarkId.Papyrus.LanguageService.Configuration.CreationKit.CreationKitProgramOptionsProvider.GetAmbientProgramOptions() in D:\a\papyrus-lang\papyrus-lang\src\DarkId.Papyrus.LanguageService\Configuration\CreationKit\CreationKitProgramOptionsProvider.cs:line 43 at DarkId.Papyrus.Server.ProjectProgramOptionsProvider.<GetProgramOptions>d__7.MoveNext() in D:\a\papyrus-lang\papyrus-lang\src\DarkId.Papyrus.Server\ProjectProgramOptionsProvider.cs:line 76 --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at System.Threading.Tasks.Task.Wait() at DarkId.Papyrus.Common.TaskExtensions.WaitForResult[T](Task`1 task) in D:\a\papyrus-lang\papyrus-lang\src\DarkId.Papyrus.Common\TaskExtensions.cs:line 12 at DarkId.Papyrus.Server.ProjectManager.UpdateProjects(UpdateProjectsOptions options) in D:\a\papyrus-lang\papyrus-lang\src\DarkId.Papyrus.Server\ProjectManager.cs:line 100 at DarkId.Papyrus.Server.Features.ProjectInfosHandler.Handle(ProjectInfosParams request, CancellationToken cancellationToken) in D:\a\papyrus-lang\papyrus-lang\src\DarkId.Papyrus.Server\Features\ProjectInfosHandler.cs:line 36 at OmniSharp.Extensions.Embedded.MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass0_0.<Handle>g__Handler|0() at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.<RouteRequest>d__11.MoveNext() ---> (Inner Exception #0) System.FormatException: Unrecognized line format: 'iExtendedResponceLength+255'. at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload) at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load() at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers) at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build() at DarkId.Papyrus.LanguageService.Configuration.CreationKit.CreationKitInisConfigLoader.LoadConfig(CreationKitIniLocations inis) in D:\a\papyrus-lang\papyrus-lang\src\DarkId.Papyrus.LanguageService\Configuration\CreationKit\CreationKitInisConfigLoader.cs:line 27 at DarkId.Papyrus.LanguageService.Configuration.CreationKit.CreationKitProgramOptionsProvider.GetAmbientProgramOptions() in D:\a\papyrus-lang\papyrus-lang\src\DarkId.Papyrus.LanguageService\Configuration\CreationKit\CreationKitProgramOptionsProvider.cs:line 43 at DarkId.Papyrus.Server.ProjectProgramOptionsProvider.<GetProgramOptions>d__7.MoveNext() in D:\a\papyrus-lang\papyrus-lang\src\DarkId.Papyrus.Server\ProjectProgramOptionsProvider.cs:line 76<---

**Comment by Morribyte** [comment]
Ohai, I had this bug last week. I actually was able to fix it by reformatting Windows and reinstalling everything again according to the process described in Mrowrpurr's Skyrim quick mod authoring setup playlist on YouTube found here: https://www.youtube.com/playlist?list=PLektTyeQhBZftc72NrPFAZDZDYdMX3bAK

I don't know if I did it wrong the first time, but once I reformatted and installed everything according to her instructions it worked fine. 

I've no idea what caused the bug, and couldn't find any of the files referenced within the stack-trace so there was no way for me to troubleshoot.

**Comment by hoskonen** [comment]
> Ohai, I had this bug last week. I actually was able to fix it by reformatting Windows and reinstalling everything again according to the process described in Mrowrpurr's Skyrim quick mod authoring setup playlist on YouTube found here: https://www.youtube.com/playlist?list=PLektTyeQhBZftc72NrPFAZDZDYdMX3bAK
> 
> I don't know if I did it wrong the first time, but once I reformatted and installed everything according to her instructions it worked fine.
> 
> I've no idea what caused the bug, and couldn't find any of the files referenced within the stack-trace so there was no way for me to troubleshoot.

Hey, thanks for the reply. Yeah, this is the series I’m following, I’m wondering can it be something to do with the new AE version of Skyrim. I might rewatch those videos and see if I did something wrong.

**Comment by hoskonen** [comment]
In the error there was line about the **iExtendedResponceLength**. I commented that line from CreationkitCustom.ini located in the game directory and there's no crashing and intellisense started working.
