### ISSUE TITLE
Which Skyrim SE versions does the DarkId.Papyrus.DebugServer.Skyrim.dll support

### ISSUE THREAD

**Issue by yountmg** [joelday/papyrus-lang#152]
Nexus has serveral versions of Skyrim SE out.  I believe the comunity refers to them as Skrim SE, AE and VR.

I have noticed that many dll's for SE do not work on AE.

The documentation never mentioned it, but does the DarkId.Papyrus.DebugServer.Skyrim.dll support Skyrim SE version 1.6.353 as well Skyrim SE version 1.5.97?

Is it difflicult to create a dll for AE?

**Comment by Xhenet** [comment]
Does not work with the AE edition for me, had to downgrade to 1.5.97 to get it running.

**Comment by nikitalita** [comment]
> Does not work with the AE edition for me, had to downgrade to 1.5.97 to get it running.

If you're feeling adventurous, AE is tested and working on my fork here: https://github.com/nikitalita/papyrus-debug-server/tree/wip-modernize

You'll have to follow the build instructions in the README. It's going to be a few weeks until I can get this into shape for a release, though.

**Comment by nsidaria** [comment]
First of all, thanks for all your work on this so far, and for everything you are yet to do.  I wish I could contribute more, but Skyrim scripting is already pushing the boundaries of my ability.

I'm trying to get the debugger working in VS Code with Skyrim AE version 1.6.640.0.
I tried to build the project forked by nikitalita, but it failed 2 of 5, and I see a lot of "cannot result in a constant expression" errors.
Not sure what to try next.

Done building project "DarkId.Papyrus.DebugServer.Skyrim.vcxproj" -- FAILED.
========== Build: 3 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
========== Elapsed 12:12.267 ==========

Looking forward to finding a way forward with this.

**Comment by nikitalita** [comment]
We have the debug server up and running in the pre-release channel. Go to vs code extensions and switch to the pre-release channel, then update the debugger when prompted when starting a debug session.

**Comment by nsidaria** [comment]
That worked perfectly. I did also have to install the Address Library for SKSE plugins (https://www.nexusmods.com/skyrimspecialedition/mods/32444) to get this working, but I got it working!!!

Thanks so much!
