### ISSUE TITLE
Update to 3.0.1 changed ${SKYRIMSE_PATH} Scripts\Source to Source\Scripts

### ISSUE THREAD

**Issue by mrowrpurr** [joelday/papyrus-lang#164]
**Describe the bug**
After a user was automatically upgraded to `3.0.1`, they reported that their builds started to fail.

They did NOT customized their `skyrimSpecialEdition.installPath`

Their `resources/sse/skyrimse.ppj` looks like this (_the default, I believe_)

```xml
<?xml version='1.0'?><!-- Game is either sse, tesv, or fo4 -->
<PapyrusProject xmlns="PapyrusProject.xsd" 
    Flags="TESV_Papyrus_Flags.flg" 
    Game="sse" 
    Output="Scripts" 
    Optimize="false" 
    Release="false" 
    Final="false">
    <Imports>
        <Import>.\Source\Scripts</Import>
        <Import>${SKYRIMSE_PATH}</Import>
    </Imports>
    <Folders>
        <Folder>.\Source\Scripts</Folder>
    </Folders>
</PapyrusProject>
```

Previously, `${SKYIMSE_PATH}` had generated:
```xml
<Import>F:\Steam Games\steamapps\common\Skyrim Special Edition\Data\Scripts\Source</Import>
```

But with `3.0.1`, it now generated `Source\Scripts` instead of the previous `Scripts\Source`:
```xml
<Import>F:\Steam Games\steamapps\common\Skyrim Special Edition\Data\Source\Scripts</Import>
```

This may presumably be impacting all users who use the default `${SKYRIMSE_PATH}`

> Note, the user in this case had their scripts unzipped to `Data\Scripts\Source` rather than `Data\Source\Scripts`

**Comment by joelday** [comment]
@mrowrpurr Looking into it now. Apologies for the disruption!

**Comment by joelday** [comment]
@mrowrpurr To confirm, did the build failures start happening for an existing project?

**Comment by mrowrpurr** [comment]
I just checked with the original reporter:
> Since I fixed it, I don't have any issues anymore. It seemed like the update reset my skyrimse.ppj and tasks.json

I think this'll just impact folks who frequently rely on the Generate Files behavior
![image](https://user-images.githubusercontent.com/87039589/210262916-32190b86-9876-4b10-98bd-e2c24a4c57f5.png)

Some folks who put their `Scripts.zip` files into `Data\Scripts\Source` will be sad.

But CK extracts into `Data\Source\Scripts` so I don't know if I'd call it a bug? I might categorize it as "surprising".

**Comment by mrowrpurr** [comment]
FYI - reporter was relying on the extension folders' `resources\sse\` template files to not change.

( _They were following guidance from a YouTube video of mine. I'll release a new video that works with 3.0.1 and fewer people will scrape their knees on this little thing. I'd call it all good? It's just a surprising change. But it feels more "correct"..._ )

**Comment by mrowrpurr** [comment]
I vote to close as: Intended Behavior

**Comment by joelday** [comment]
@mrowrpurr I think this may have been a change from a long time ago that was never actually released until the accidental 3.x release. Thanks for looking into it!

**Comment by joelday** [comment]
By the way, @mrowrpurr, we will be making more significant changes soon, which will probably result in an uptick of questions coming your way. We'll do our best to communicate it to users as new versions are installed, but new users will likely encounter things that don't quite match things now. (Manually replacing old Pyro, for example.)

We're actively discussing these things on [Discord](https://discord.gg/E4dWujQ), so that'll be the best way to get a heads-up going forward.

Thank you so much for all of this support and knowledge sharing!
