### ISSUE TITLE
Server crashes when a psc file is opened without an active workspace

### ISSUE THREAD

**Issue by joelday** [joelday/papyrus-lang#18]

**Comment by Scrivener07** [comment]
With at least [v2.12.1](https://github.com/joelday/papyrus-lang/releases/tag/v2.12.1) I can confirm this works for a simple script in a single file workspace.

`E:\Games\Steam\steamapps\common\Fallout 4\Data\Scripts\Source\User\Example.psc`
```
Scriptname Example

Event OnInit()
	Debug.Trace("Hello World!")
EndEvent
```
