### ISSUE TITLE
Pyro project discovery support

### ISSUE THREAD

**Issue by joelday** [joelday/papyrus-lang#19]
Support for https://github.com/fireundubh/pyro yaml project format. Also ensure that XML deserializer is relaxed to allow Pyro's extended attributes.

**Comment by minkir014** [comment]
Pyro system doesn't currently support yaml except that it's projects are ordinary projects it's an ordinary build system

**Comment by joelday** [comment]
@minkir014 Just have this as a task for later.

**Comment by rjstone** [comment]
Yes Pyro support is implemented. Full pyro ahead.... Closing.,,,
