### ISSUE TITLE
Variable name "MyProperty" has wrong syntax coloring.

### ISSUE THREAD

**Issue by Scrivener07** [joelday/papyrus-lang#2]
Variable name "MyProperty" has wrong syntax coloring. The Property language keyword colorizes the variable name partially. I have attached a screen capture below.
![issue](https://user-images.githubusercontent.com/1912967/44635801-15b1a980-a976-11e8-875f-8332ae1a7a23.png)

This applies to at least [v0.0.1-preview.1](https://github.com/joelday/papyrus-lang/releases/tag/v0.0.1-preview.1)

**Comment by Scrivener07** [comment]
This is probably related to something in the language definition.

7f620a4 [src/papyrus-lang-vscode/syntaxes/papyrus/papyrus.tmLanguage](https://github.com/joelday/papyrus-lang/blob/2e13f0542911c981dc0d53569b9f24d2cfa6984a/src/papyrus-lang-vscode/syntaxes/papyrus/papyrus.tmLanguage)

**Comment by UrbanCMC** [comment]
This was fixed in #137.

**Comment by Scrivener07** [comment]
![Capture](https://user-images.githubusercontent.com/1912967/90272874-10341f00-de2c-11ea-9be5-9d122cde5949.PNG)
Confirmed, thanks for the heads up.
