### ISSUE TITLE
Add feature preview GIFs to README.md

### ISSUE THREAD

**Issue by Scrivener07** [joelday/papyrus-lang#26]
The `README.md` could use some preview GIFs to briefly show each major extension feature.

**Details**
- Recorder: LICEcap
- Dimensions: 800x575
- FPS: 30

**Notes**
- Use the default VS Code theme.
- Keep the mouse work clean and smooth.
- Keep typing smooth. Only stop briefly at the end of each symbol.
- Avoid sample code that runs off the horizontal view.
- Use VS Code's UI zoom (ctrl-+) for high dpi recordings.
- Be slow & simple enough to see what's going on. 
- Disable `Render Whitespace`.
- Disable `Minimap`.
- Remove anything that may distract from the feature being previewed.

#### Code Completion
![Feature_CodeCompletion](https://user-images.githubusercontent.com/1912967/54874927-09d27c80-4dcb-11e9-9b40-33de897e7226.gif)

#### Go to Definition & Peek Definition
![Feature_JumpToDefinition](https://user-images.githubusercontent.com/1912967/54875750-d13a9f00-4dda-11e9-8e2f-92ec263d74fc.gif)

#### Symbol Outline & Breadcrumbs
![Feature_SymbolOutline](https://user-images.githubusercontent.com/1912967/54875884-32fc0880-4ddd-11e9-8897-3f2e0e25a0d2.gif)

**Comment by joelday** [comment]
I think these are good. :)
