### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by FelesNoctis** [joelday/papyrus-lang#29]
**Describe the bug:**
When opening a `.pyc` script file after a fresh install of papyrus-lang, the output console reports the titular error message for Skyrim and Skyrim SE, but **not** Fallout 4.

**To Reproduce:**
Assumption is a typo in the language service script provided with the extension.

The paths for all three games appear to be correct, each game's unique CK is installed and updated, the ini files are all in place, the base scripts are extracted to their associated locations, and the `.flg` files exist. I did notice that the `Papyrus Compiler` folders appear to be lacking files compared to the Fallout 4 version, if that's relevant in any way.

**VSC Output Logs:**
```Creating Language Client instance with options:
{"compilerAssemblyPath":"f:\\Games\\steamapps\\common\\Fallout 4\\Papyrus Compiler",
"creationKitInstallPath":"f:\\Games\\steamapps\\common\\Fallout 4",
"relativeIniPaths":["CreationKit.ini","CreationKitCustom.ini"],
"flagsFileName":"Institute_Papyrus_Flags.flg",
"ambientProjectName":"Fallout 4 Creation Kit",
"defaultScriptSourceFolder":"\".\\Data\\Scripts\\Source\\User\"",
"defaultAdditionalImports":"\"$(source);.\\Data\\Scripts\\Source\\Base\""}
Starting language service...
Language service started.
[Info  - 11:19:22 PM] Searching for Papyrus projects in c:\Users\bwfan\gitprojects\wrye-bash-grndbeef...
[Info  - 11:19:22 PM] Found 0 project(s) in c:\Users\bwfan\gitprojects\wrye-bash-grndbeef:

[Info  - 11:19:22 PM] Resolving script files for Fallout 4 Creation Kit...
```

```Creating Language Client instance with options:
{"compilerAssemblyPath":"F:\\Games\\steamapps\\common\\Skyrim Special Edition\\Papyrus Compiler",
"creationKitInstallPath":"F:\\Games\\steamapps\\common\\Skyrim Special Edition\\",
"relativeIniPaths":["CreationKit.ini","CreationKitCustom.ini"],
"flagsFileName":"TESV_Papyrus_Flags.flg",
"ambientProjectName":"Skyrim SE Creation Kit",
"defaultScriptSourceFolder":".\\Data\\Source\\Scripts\\"}
Error on language service pre-start: TypeError: Cannot read property 'toString' of undefined
```

```Creating Language Client instance with options:
{"compilerAssemblyPath":"F:\\Games\\steamapps\\common\\Skyrim\\Papyrus Compiler",
"creationKitInstallPath":"F:\\Games\\steamapps\\common\\Skyrim\\",
"relativeIniPaths":["SkyrimEditor.ini"],
"flagsFileName":"TESV_Papyrus_Flags.flg",
"ambientProjectName":"Skyrim Creation Kit",
"defaultScriptSourceFolder":"\"Data\\Scripts\\Source\""}
Error on language service pre-start: TypeError: Cannot read property 'toString' of undefined
```

**Screenshots:**
[Fallout 4](https://i.imgur.com/KgpjNox.png)
[Skyrim SE](https://i.imgur.com/8FOdsCg.png)
[Skyrim LE](https://i.imgur.com/5fZfyTn.png)

**Comment by joelday** [comment]
@FelesNoctis I've added some additional logging. Can you upgrade to 2.0.7 and paste in the stack trace? Thank you!

**Comment by FelesNoctis** [comment]
I am but a humble jack-of-all-trades, so I'm going to hope this is what you're looking for?
https://pastebin.com/T6sgUnri

**Comment by joelday** [comment]
@FelesNoctis should be fixed!

**Comment by FelesNoctis** [comment]
![All checks are go!](https://i.imgur.com/nnhToxX.png)
Looks like it, thank you! :smile:
