### ISSUE TITLE
Document strings and comments catch auto completion when a `dot` is used.

### ISSUE THREAD

**Issue by Scrivener07** [joelday/papyrus-lang#3]
Document strings and comments catch auto completion when a dot is used.

![issue1](https://user-images.githubusercontent.com/1912967/44635951-dfc0f500-a976-11e8-8647-12e35b7a5e29.png)
![issue2](https://user-images.githubusercontent.com/1912967/44635952-dfc0f500-a976-11e8-9ae8-4abce619ca5b.png)
![issue3](https://user-images.githubusercontent.com/1912967/44635953-dfc0f500-a976-11e8-9e0a-0cb403ca90d4.png)

**Comment by joelday** [comment]
Fixed in 0.7.0. Thanks!
