### ISSUE TITLE
Custom compiler path

### ISSUE THREAD

**Issue by Qudix** [joelday/papyrus-lang#33]
At the moment, the extension defaults to:
\Fallout 4\Papyrus Compiler\

I moved this folder into the tools folder like so:
\Fallout 4\Tools\Papyrus Compiler\

for organization. Currently there is no way to change this behaviour.

**Comment by joelday** [comment]
The extension currently supports `sCompilerPath` in CK's ini files. Let me know if that works for you or not.

**Comment by Qudix** [comment]
That does seem to work.

**Comment by joelday** [comment]
@Qudix for future reference, this should actually be `sCompilerFolder`. I kept support for both so it wouldn't break for you.
