### ISSUE TITLE
Skyrim file resolution should not be recursive

### ISSUE THREAD

**Issue by joelday** [joelday/papyrus-lang#37]
Currently any subdirectory (such as those for DLC) in an included directory will emit errors with no context for why.

**Comment by minkir014** [comment]
Have you tried to open the subdirectory as a workspace

**Comment by joelday** [comment]
@minkir014 Totally. This is just to prevent errors that don't mean anything since there are no namespaces in Skyrim.

**Comment by minkir014** [comment]
But for now you can separate the subdirectory on another vscode window. I think this will work. And you said that Skyrim doesn't have namespaces now. Maybe you have to change the syntax to prevent this error. I think when you change the syntax and make it as Skyrim has now. That will solve the issue.

**Comment by joelday** [comment]
@minkir014 Everything will work if the scripts in those sub-directories are included at the root level in the active "project", but currently you see a bunch of meaningless errors complaining about the filenames being incorrect.

**Comment by minkir014** [comment]
Maybe it's not in your extension but in the project settings. If you set the configuration of the project to the multiple root. This might solve your issue.

**Comment by minkir014** [comment]
@joelday Where are you?

**Comment by Scrivener07** [comment]
@minkir014 Hey friend, check out the latest version.
