### ISSUE TITLE
Add Ability To Generate Papyrus Project Files

### ISSUE THREAD

**Issue by Deadmano** [joelday/papyrus-lang#41]
It'd be great if the extension could automatically generate .ppj files based on the Workspace currently loaded and the files/folders therein. It can already detect the game and its location, so that's pretty much all that is needed to create a .ppj file.

**Comment by minkir014** [comment]
It's easy to be done make extension to integrated terminal when clicking the button create project.

**Comment by Scrivener07** [comment]
Related to issue #56

**Comment by Scrivener07** [comment]
Moved to issue #56
