### ISSUE TITLE
Defined Functions not detected in Skyrim LE

### ISSUE THREAD

**Issue by WYVERN2742** [joelday/papyrus-lang#45]
**Describe the bug**
Functions defined in papyrus files are not shown in the outline, nor showup in the autocompletions within the script.

**To Reproduce**
1. Create a correct workspace for skyrim LE
2. Create a correct papyrus file that contains a function
3. Function not detected, but properties and variables are.

![2019-06-08_20-44-12](https://user-images.githubusercontent.com/35181365/59151157-2f643f00-8a26-11e9-9594-3a9ac0aea02d.gif)

As seen in the gif above, the two declared functions do not exist in the outline, nor show up during intellisense.

**Comment by joelday** [comment]
@WYVERN2742 does this still happen for you in the latest version?

**Comment by WYVERN2742** [comment]
Fixed in latest.
