### ISSUE TITLE
Debugger variables panel only shows function arguments and object inheritance. 

### ISSUE THREAD

**Issue by Scrivener07** [joelday/papyrus-lang#47]
Debugger variables panel only shows function arguments and object inheritance. Properties and fields seem to be missing. For example with this code.
```papyrus
Scriptname Example extends Actor
{The documentation string.}

; Fields
;--------------------------------------------

int Count = 0

; Properties
;--------------------------------------------

Group KeyCodes
	int Property Left = 37 AutoReadOnly
	int Property Right = 39 AutoReadOnly
EndGroup

; Events
;--------------------------------------------

Event OnInit()
	RegisterForKey(Left)
	RegisterForKey(Right)
EndEvent

Event OnKeyDown(int keyCode)
	If (keyCode == Left)
		Count -= 1
		Debug.TraceSelf(self, "OnKeyDown", "Increased the count to "+Count)
	ElseIf (keyCode == Right)
		Count += 1
		Debug.TraceSelf(self, "OnKeyDown", "Decreased the count to "+Count)
	Else
		Debug.TraceSelf(self, "OnKeyDown", "The key "+keyCode+" is unhandled.")
	EndIf
EndEvent
```

Will result in.
![Capture](https://user-images.githubusercontent.com/1912967/59180078-f618f580-8b31-11e9-8a1a-6df27cfa1045.PNG)

**Comment by Scrivener07** [comment]
Here is a standalone sample mod Ive been testing with in game. Includes source and also compiled and ready to use in game.
[VSCode - Debug Mod Sample.zip](https://github.com/joelday/papyrus-lang/files/3271076/VSCode.-.Debug.Mod.Sample.zip)

**Comment by joelday** [comment]
@Scrivener07 Do the properties, etc. show up if you expand the 'self' variable?

**Comment by Scrivener07** [comment]
No it only shows a tree for the object inheritance (self > Actor > ObjectReference > etc).
