### ISSUE TITLE
Debugger will crash the game to desktop if attached *while* game is loading.

### ISSUE THREAD

**Issue by Scrivener07** [joelday/papyrus-lang#49]
The Debugger will crash the game to desktop if attached while game is loading. An example of this happening is shown in the first part of this video. Logs are included in the description. This is also probably not a bug, but Ill let you decide in case its a symptom of something that is a bug.

https://www.youtube.com/watch?v=937DVe2t8lI

**Comment by joelday** [comment]
@Scrivener07 I've seen this, but it wasn't a 100% repro. Let me know if this happens every time for you.

**Comment by Scrivener07** [comment]
**Describe the bug**
Debugger will crash the game to desktop if attached *while* game is loading.

**To Reproduce**
Steps to reproduce the behavior:

1. Launch the Game and remain at the main menu.
2. Launch VS Code.
3. Attach VS Code debugger to the Game.
4. Focus the Game and open the developer console and execute `coc RedRocketExt`
5. * This may or may not matter but while the Game is loading I change application focus back to VS Code.
6. When I switch focus back to the Game it does not crash immediately but will crash as soon as the loading screen is done.

**Comment by Scrivener07** [comment]
It the debugger does not crash anymore with at least commit 2e0a64b (v2.9.3).

**Comment by Scrivener07** [comment]
This is definitively fixed. Here is a video of it working now [Joel Day, VS Code, Live Papyrus Debugging, Test 8, v2.9.3](https://youtu.be/U3EGKQ3ofqM). Closing this and thanks.
