### ISSUE TITLE
Add `Create Project PPJ` command and basic project scaffolding.

### ISSUE THREAD

**Issue by Scrivener07** [joelday/papyrus-lang#56]
### Describe
This is a feature request for papyrus project scaffolding.
Add `Create Project` command that auto-fills to match the ini configuration and provides basic scaffolding. I would imagine it should create a folder with that name, and put the ppj in there too.
This could work by right clicking on the VS Code file explorer.

### Details
1. Add a `Create Project` command.
2. Add the `Create Project` command to the VS Code file explorer context menu.

**Comment by Scrivener07** [comment]
Whoopsie. This is probably a duplicate of issue #41

**Comment by Scrivener07** [comment]
Hey Deadmano. I accidentally made this as a duplicate issue but now that its here Im going to mark yours as the duplicate. I also moved your issue content here as a comment. This is so I can update the original post and track feature status. Thanks for creating the initial issue. 

@Deadmano mentioned in issue #41
> It'd be great if the extension could automatically generate .ppj files based on the Workspace currently loaded and the files/folders therein. It can already detect the game and its location, so that's pretty much all that is needed to create a .ppj file.
This should be covered by generating a ppj from the Creation Kit *.ini configuration or right clicking a folder in the workspace file explorer.

**Comment by Scrivener07** [comment]
I wonder how much issue #19 Pyro project discovery support will complicate this.

**Comment by rjstone** [comment]
I created something like this here https://www.nexusmods.com/skyrimspecialedition/mods/29491?tab=description but it is skyrimse-specific at the moment and not generated by the extension. Assuming a PPJ is added, how close does this come to the goal?

**Comment by minkir014** [comment]
Maybe, I have an idea why don't you make this command sends to the terminal the command that is used to generate a project. And what will be sent must have all information about the place that the project will be created in.

**Comment by rjstone** [comment]
This is now present in the latest release. Skyrim LE (Classic) is missing but I can add that in 2 seconds.

**Comment by Deadmano** [comment]
Can you add Skyrim LE (classic) support? As this is something a few of us
still use or support.

**Comment by rjstone** [comment]
Yep, I just created an issue for that. it's the easiest thing to add so I'll do that today.
