### ISSUE TITLE
Logos, Icons, and Branding Media

### ISSUE THREAD

**Issue by Scrivener07** [joelday/papyrus-lang#62]
##### -Joel
> Really the highest priority for us should be getting a logo that looks okay in a circle.

## Needs
What we need from someone with artistic skills.

### Extension Icon
An icon/logo for this extension. See also [VS Code Extension Manifest Icons](https://code.visualstudio.com/api/references/extension-manifest#fields).
* Must look good in a circle.
* Must have a full icon set of sizes from at least `16x16px` to `256x256px` . (`256x256px` for Retina screens).
* Optionally, a full set of sizes with stylized per-game.

### Social Preview Image
Add GitHub's new Social preview image.
* Images should be at least `640×320px` (`1280×640px` for best display).
* Template describes that there should be a `40px` (`80px`?) margin.

### File Type Icons
Possibly a new [VS Code Icon Theme](https://code.visualstudio.com/api/extension-guides/icon-theme) for files related to modding Bethesda games. See also the [Icon Theme Extension Guide](https://code.visualstudio.com/api/extension-guides/icon-theme).
* A full set of sizes from at least `16x16` to `128x128` for each file type .

**Comment by Scrivener07** [comment]
The highest priority.

**Comment by joelday** [comment]
So what, you're saying I don't have artistic skills?

Let's add GitHub's new Social preview image. "Images should be at least 640×320px (1280×640px for best display)." Template describes that there should be a 40px (80px?) margin.

**Comment by Scrivener07** [comment]
Its an open casting call. Your welcome to try out. x)

**Comment by joelday** [comment]
> a new [VS Code Icon Theme](https://code.visualstudio.com/api/extension-guides/icon-theme) for files related to modding Bethesda games

I still haven't determined if it's possible for us to contribute a limited subset of icons that are automatically shown if they don't conflict with the user's current chosen icon theme. I asked on Gitter, but didn't get a response, so I suppose we'll just have to give it a shot.

**Comment by Scrivener07** [comment]
Its also not a fully formed idea yet. We can always sit on the Icon Theme idea for a while too or break it off into its own issue if needed.

**Comment by Scrivener07** [comment]
These are all the Creation Kit object type icons. Almost all the game data objects have an associated icon.
![CreationKit_Objects](https://user-images.githubusercontent.com/1912967/60029321-ec81a880-966e-11e9-8a63-1a7cee699e33.png)

I have extracted the assets from the Creation Kit assemblies and have all the included art. In particular I have the above bitmap separated into individual `png` files which are ready to use.

[EditorIcons_16x16_PNG_CreationKit.zip](https://github.com/joelday/papyrus-lang/files/3321389/EditorIcons_16x16_PNG_CreationKit.zip)

* Armor ![tile001](https://user-images.githubusercontent.com/1912967/60029653-906b5400-966f-11e9-82e2-5f55b7bfc210.png)
* Book ![tile002](https://user-images.githubusercontent.com/1912967/60029656-919c8100-966f-11e9-886b-b3f4d4e23e32.png)
* Perk ![tile039](https://user-images.githubusercontent.com/1912967/60029703-a6791480-966f-11e9-8b41-2d63412c3cc2.png)
* Action ![tile031](https://user-images.githubusercontent.com/1912967/60029812-d45e5900-966f-11e9-968e-ae3252153e11.png)
* Leveled Item ![tile018](https://user-images.githubusercontent.com/1912967/60029826-d9230d00-966f-11e9-894d-505beee91989.png)
* Activator ![tile000](https://user-images.githubusercontent.com/1912967/60029836-dde7c100-966f-11e9-816d-9ffdb10f561d.png)
* Sound Descriptor ![tile023](https://user-images.githubusercontent.com/1912967/60029857-e8a25600-966f-11e9-989b-cbfeb77ae02a.png)
* Quest ![tile046](https://user-images.githubusercontent.com/1912967/60029972-2606e380-9670-11e9-9268-805f809b528c.png)

Thats for some ideas.

**Comment by Scrivener07** [comment]
![Capture](https://user-images.githubusercontent.com/1912967/60161101-cff78480-97c4-11e9-9be5-078a68058876.PNG)
![Capture](https://user-images.githubusercontent.com/1912967/60161171-f1f10700-97c4-11e9-9adb-3d3f79fa2782.PNG)
![Capture](https://user-images.githubusercontent.com/1912967/60161248-249aff80-97c5-11e9-9724-a9308feaa59f.PNG)

**Download**
[CreationKit_AssemblyResources.zip](https://github.com/joelday/papyrus-lang/files/3328885/CreationKit_AssemblyResources.zip)


This is what I have on-hand for maintaining any iconography between tools. One of note is the property icons related to the Papyrus script property editor. 
![Capture](https://user-images.githubusercontent.com/1912967/60161587-d89c8a80-97c5-11e9-899f-c6bc51b242f1.PNG)

Ill just leave this all here for later in case it might become useful.

**Comment by rjstone** [comment]
I have experience with designing vector graphics and I know how to use stuff like Illustrator so I could possibly help with this.

**Comment by joelday** [comment]
> These are all the Creation Kit object type icons. Almost all the game data objects have an associated icon. ![CreationKit_Objects](https://user-images.githubusercontent.com/1912967/60029321-ec81a880-966e-11e9-8a63-1a7cee699e33.png)
> 
> I have extracted the assets from the Creation Kit assemblies and have all the included art. In particular I have the above bitmap separated into individual `png` files which are ready to use.
> 
> [EditorIcons_16x16_PNG_CreationKit.zip](https://github.com/joelday/papyrus-lang/files/3321389/EditorIcons_16x16_PNG_CreationKit.zip)
> 
> * Armor ![tile001](https://user-images.githubusercontent.com/1912967/60029653-906b5400-966f-11e9-82e2-5f55b7bfc210.png)
> * Book ![tile002](https://user-images.githubusercontent.com/1912967/60029656-919c8100-966f-11e9-886b-b3f4d4e23e32.png)
> * Perk ![tile039](https://user-images.githubusercontent.com/1912967/60029703-a6791480-966f-11e9-8b41-2d63412c3cc2.png)
> * Action ![tile031](https://user-images.githubusercontent.com/1912967/60029812-d45e5900-966f-11e9-968e-ae3252153e11.png)
> * Leveled Item ![tile018](https://user-images.githubusercontent.com/1912967/60029826-d9230d00-966f-11e9-894d-505beee91989.png)
> * Activator ![tile000](https://user-images.githubusercontent.com/1912967/60029836-dde7c100-966f-11e9-816d-9ffdb10f561d.png)
> * Sound Descriptor ![tile023](https://user-images.githubusercontent.com/1912967/60029857-e8a25600-966f-11e9-989b-cbfeb77ae02a.png)
> * Quest ![tile046](https://user-images.githubusercontent.com/1912967/60029972-2606e380-9670-11e9-9268-805f809b528c.png)
> * etc...
> 
> Thats for some ideas.

It could be cool to use these for something in the extension, possibly in Project Explorer, based on matching Form types.

**Comment by joelday** [comment]
#70

**Comment by Scrivener07** [comment]
Ill drop this link here which maps the class name to which icon it belongs to. Not all classes have an associated icon.

https://falloutck.uesp.net/wiki/Category:Object_Classes
