### ISSUE TITLE
Cursor should move outside of right paren for code completion of functions that have no arguments

### ISSUE THREAD

**Issue by joelday** [joelday/papyrus-lang#67]
`int blah = GetWhatever()*cursor goes here*`

**Comment by Scrivener07** [comment]
![github_issue_67_1](https://user-images.githubusercontent.com/1912967/59970049-04e8aa80-952b-11e9-8680-9190fb75a39a.gif)
![github_issue_67_2](https://user-images.githubusercontent.com/1912967/59970050-074b0480-952b-11e9-9dc0-01b18e91b658.gif)


The autocomplete doesnt seem to insert parenthesis or parameters at all. The above gif shows what I mean.

**Comment by joelday** [comment]
Well then, this is not a bug. :)
