### ISSUE TITLE
IntelliSense, suggest snippet insertion for overriding inherited events and functions.

### ISSUE THREAD

**Issue by Scrivener07** [joelday/papyrus-lang#77]
**Describe the bug**
This sounds a little like issue #44.
IntelliSense should suggest snippet insertions in child scripts for overriding inherited events and functions. The majority of scripts work by overriding inherited native base events with an implementation in children scripts.

**To Reproduce**
1. Create a new script.
2. Attempt to implement the `OnInit` event which is inherited on every script for skyrim and fallout.
3. Notice there are no suggestions, and events must be typed out along with their parameters.

**Comment by minkir014** [comment]
So, Is that a problem with intellisense or snippets system?


I mean If snippets isn't filling the appropriate arguments so It's not a problem with intellisense?
but if you mean when you type ordinary script without using snippets auto suggestion doesn't work then It's a problem with intellisense..

**Comment by Scrivener07** [comment]
This is more of an enhancement than a bug for IntelliSense. More accurately the language service which powers the IntelliSense widget.

None of the contextually aware suggestions within IntelliSense are snippets at all. The IntelliSense widgets displays snippets in its list but they are not truly part of the IntelliSense system.
These snippet entries are marked with the snippet icon (![Snippet_16x](https://user-images.githubusercontent.com/1912967/60378400-1846ba80-99f0-11e9-8cf1-b11866bacb71.png)) and are not truly part of the language service.

I bring this up because if your getting an `OnInit` snippet suggestion then you are using another Papyrus extension alongside this one.

**Comment by minkir014** [comment]
No I said what I understood from your title..

> IntelliSense, suggest snippet insertion for overriding inherited events and functions.

So It's a problem with suggestion. Is that right??

**Comment by joelday** [comment]
@minkir014 This is just a feature request that is equivalent of what C# provides when you begin typing `overrides`.
