### ISSUE TITLE
No Issue: Just wanted to say thanks.

### ISSUE THREAD

**Issue by ogrotten** [joelday/papyrus-lang#80]
I've been using a different plugin but just discovered this one today. Thanks and Nice work.

Oh and my favorite part is where the "Won't fix" tag is unused!

Can't wait for (skyrim) compiler support!

**Comment by joelday** [comment]
@ogrotten Somehow I missed this. Thank you!

**Comment by rjstone** [comment]
Check it out now... it's even better!
