### ISSUE TITLE
Debugger: Quest script showing error: "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by SMB92** [joelday/papyrus-lang#81]
One of my main Quest scripts keeps showing the error: "Object reference not set to an instance of an object." Not really sure what is going on here, no other errors being highlighted. Another script that has this script linked as an property complains it's an unknown type, but not all scripts with this linked have this problem.  

Please find attached snips of the issue as listed in VSC. 
![error_01](https://user-images.githubusercontent.com/37429946/60899041-25479180-a2ad-11e9-9b34-b5924b876260.PNG)
![error_02](https://user-images.githubusercontent.com/37429946/60899053-2bd60900-a2ad-11e9-9480-decf1aee00c4.PNG)

**To Reproduce**

1. Behavior is consistent between sessions.

**Comment by Scrivener07** [comment]
On closer inspection via direct message on Discord, an error was found to be located in the user's code base. @SMB92 Im closing this for now but please reopen this if the issue persists even after you resolve your compiler errors.

**Comment by Scrivener07** [comment]
Joel agreed that the extension error message is a bit confusing so this is a possible improvement for the future.
