### ISSUE TITLE
Don't know how to add a project to papyrus project explorer

### ISSUE THREAD

**Issue by TheFBplus** [joelday/papyrus-lang#86]
I know the question sounds stupid,but I have tried many ways and none of them seems to be right.My explorer is like this:
![image](https://user-images.githubusercontent.com/33896027/61644202-d9e2a980-acd6-11e9-8661-0bc70ee73645.png)
how can I add project like you did:
![image](https://user-images.githubusercontent.com/33896027/61644318-0c8ca200-acd7-11e9-853a-c40c530c5f5d.png)
I open a folder directly but it looks like this:
![image](https://user-images.githubusercontent.com/33896027/61644518-7442ed00-acd7-11e9-8a77-59ec6521479c.png)
And how can I compile the psc file?Am I suppose  to use command line?Is there a more convenient way? 
I have read all the tutorial but I just could not find the solution.Can you give me some advice?
BTW I'm so sorry for my awful English, It becomes even more difficult to write than to read.I hope you can understand what I am talking about.Thanks a lot.

**Comment by joelday** [comment]
@TheFBplus I only know one language! You have nothing to apologize for.

It will automatically discover .ppj files in the folder you have open. Otherwise, it will include scripts that can be found based on the paths in your CreationKit.ini.

We have an open issue to make it easier to create new .ppj files, especially because Skyrim developers are usually not familiar with them.

**Comment by joelday** [comment]
At one point in the past, the folder you had open was treated as a "project", but that led to a lot of confusing errors for developers who didn't want to open their scripts folder directly.

**Comment by TheFBplus** [comment]
Oh,I see.It's all about the .ppj files,and yes I haven't play any fallout games before,so I just skip that part in the tutorial,my bad :pensive:
I will try it later when I come home from work.Thanks for your replay!

**Comment by TheFBplus** [comment]
I tried to crate the .ppj file manually but it still didn't work:
![image](https://user-images.githubusercontent.com/33896027/61717797-54253380-ad94-11e9-8117-2c7fec6ed1f7.png)
![image](https://user-images.githubusercontent.com/33896027/61717861-7028d500-ad94-11e9-8a7d-a9a41ccaeb43.png)
Am I missing something?Since I am totally a novice to fallout game,my question may sounds stupid,forgive me:joy:

**Comment by Scrivener07** [comment]
```xml
<?xml version='1.0'?>
<!-- http://www.creationkit.com/fallout4/index.php?title=Papyrus_Projects -->
<PapyrusProject
	xmlns="PapyrusProject.xsd"
	Flags="TESV_Papyrus_Flags.flg"
	Output="..\..\"
	Asm="Discard"
	Optimize="false"
	Release="false"
	Final="false"
>
	<Imports>
		<Import>.</Import>
		<Import>..\Base</Import>
	</Imports>
	<Folders>
		<Folder>.</Folder>
	</Folders>
</PapyrusProject>
```
It looks like you nearly got it. The main difference between ours is the `TESV_Papyrus_Flags.flg`. The institute flag file indicates the project is for fallout. Use `TESV_Papyrus_Flags.flg` for skyrim.

I was too lazy to retype your files paths from the images but your `Imports` and `Folders` elements looked good.

**Comment by TheFBplus** [comment]
@Scrivener07 Thanks a lot,finally it works 😄 
![image](https://user-images.githubusercontent.com/33896027/61806119-b8fe8d80-ae69-11e9-99c6-05e37aef817b.png)
Just like coming to the 21st century haha,I can get rid of my notepad now.
